# These are supported funding model platforms


patreon: # patreon.com/w_wachira https://patreon.com/w_wachira?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
ko_fi: # wwachira
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username

